package Hello;


/**
* Hello/HelloCorba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Sunday, January 25, 2015 1:37:31 PM CET
*/

public interface HelloCorba extends HelloCorbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HelloCorba
