package Hello;


/**
* Hello/HelloCorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Sunday, January 25, 2015 1:37:31 PM CET
*/

public interface HelloCorbaOperations 
{
  String sayHello ();
} // interface HelloCorbaOperations
