package Hello;

/**
* Hello/HelloCorbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Sunday, January 25, 2015 1:37:31 PM CET
*/

public final class HelloCorbaHolder implements org.omg.CORBA.portable.Streamable
{
  public Hello.HelloCorba value = null;

  public HelloCorbaHolder ()
  {
  }

  public HelloCorbaHolder (Hello.HelloCorba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Hello.HelloCorbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Hello.HelloCorbaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Hello.HelloCorbaHelper.type ();
  }

}
