package echoCor;


/**
* echoCor/Echo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from echo.idl
* Sunday, January 25, 2015 3:43:21 PM CET
*/

public interface Echo extends EchoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Echo
