package echoCor;


/**
* echoCor/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from echo.idl
* Sunday, January 25, 2015 3:43:21 PM CET
*/

public interface EchoOperations 
{
  String echoString (String msg);
} // interface EchoOperations
