package echoCor;

/**
* echoCor/EchoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from echo.idl
* Sunday, January 25, 2015 3:43:21 PM CET
*/

public final class EchoHolder implements org.omg.CORBA.portable.Streamable
{
  public echoCor.Echo value = null;

  public EchoHolder ()
  {
  }

  public EchoHolder (echoCor.Echo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = echoCor.EchoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    echoCor.EchoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return echoCor.EchoHelper.type ();
  }

}
