package Hello;


/**
* Hello/HelloCorba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from helloCorba.idl
* Sunday, January 25, 2015 11:45:38 AM CET
*/

public interface HelloCorba extends HelloCorbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HelloCorba
