// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "corba.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



Hello::HelloCorba_ptr Hello::HelloCorba_Helper::_nil() {
  return ::Hello::HelloCorba::_nil();
}

::CORBA::Boolean Hello::HelloCorba_Helper::is_nil(::Hello::HelloCorba_ptr p) {
  return ::CORBA::is_nil(p);

}

void Hello::HelloCorba_Helper::release(::Hello::HelloCorba_ptr p) {
  ::CORBA::release(p);
}

void Hello::HelloCorba_Helper::marshalObjRef(::Hello::HelloCorba_ptr obj, cdrStream& s) {
  ::Hello::HelloCorba::_marshalObjRef(obj, s);
}

Hello::HelloCorba_ptr Hello::HelloCorba_Helper::unmarshalObjRef(cdrStream& s) {
  return ::Hello::HelloCorba::_unmarshalObjRef(s);
}

void Hello::HelloCorba_Helper::duplicate(::Hello::HelloCorba_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

Hello::HelloCorba_ptr
Hello::HelloCorba::_duplicate(::Hello::HelloCorba_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

Hello::HelloCorba_ptr
Hello::HelloCorba::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


Hello::HelloCorba_ptr
Hello::HelloCorba::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

Hello::HelloCorba_ptr
Hello::HelloCorba::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_HelloCorba _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_HelloCorba* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_HelloCorba;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* Hello::HelloCorba::_PD_repoId = "IDL:Hello/HelloCorba:1.0";


Hello::_objref_HelloCorba::~_objref_HelloCorba() {
  
}


Hello::_objref_HelloCorba::_objref_HelloCorba(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::Hello::HelloCorba::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
Hello::_objref_HelloCorba::_ptrToObjRef(const char* id)
{
  if (id == ::Hello::HelloCorba::_PD_repoId)
    return (::Hello::HelloCorba_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::Hello::HelloCorba::_PD_repoId))
    return (::Hello::HelloCorba_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for Hello::HelloCorba::sayHello

// Proxy call descriptor class. Mangled signature:
//  _cstring
class _0RL_cd_a14b9b98917b96d4_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_a14b9b98917b96d4_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var result;
};

void _0RL_cd_a14b9b98917b96d4_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalString(result,0);

}

void _0RL_cd_a14b9b98917b96d4_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalString(0);

}

const char* const _0RL_cd_a14b9b98917b96d4_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_a14b9b98917b96d4_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_a14b9b98917b96d4_00000000* tcd = (_0RL_cd_a14b9b98917b96d4_00000000*)cd;
  Hello::_impl_HelloCorba* impl = (Hello::_impl_HelloCorba*) svnt->_ptrToInterface(Hello::HelloCorba::_PD_repoId);
  tcd->result = impl->sayHello();


}

char* Hello::_objref_HelloCorba::sayHello()
{
  _0RL_cd_a14b9b98917b96d4_00000000 _call_desc(_0RL_lcfn_a14b9b98917b96d4_10000000, "sayHello", 9);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}

Hello::_pof_HelloCorba::~_pof_HelloCorba() {}


omniObjRef*
Hello::_pof_HelloCorba::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::Hello::_objref_HelloCorba(ior, id);
}


::CORBA::Boolean
Hello::_pof_HelloCorba::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::Hello::HelloCorba::_PD_repoId))
    return 1;
  
  return 0;
}

const Hello::_pof_HelloCorba _the_pof_Hello_mHelloCorba;

Hello::_impl_HelloCorba::~_impl_HelloCorba() {}


::CORBA::Boolean
Hello::_impl_HelloCorba::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "sayHello")) {

    _0RL_cd_a14b9b98917b96d4_00000000 _call_desc(_0RL_lcfn_a14b9b98917b96d4_10000000, "sayHello", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
Hello::_impl_HelloCorba::_ptrToInterface(const char* id)
{
  if (id == ::Hello::HelloCorba::_PD_repoId)
    return (::Hello::_impl_HelloCorba*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::Hello::HelloCorba::_PD_repoId))
    return (::Hello::_impl_HelloCorba*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
Hello::_impl_HelloCorba::_mostDerivedRepoId()
{
  return ::Hello::HelloCorba::_PD_repoId;
}

POA_Hello::HelloCorba::~HelloCorba() {}

