TOP=$(HOME)/bin/omniORB-4.2.0
CURRENT=$(HOME)/bin/omniORB-4.2.0/src/examples/echo
BASE_OMNI_TREE=$(HOME)/bin/omniORB-4.2.0

INSTALL=/usr/bin/install -c

include $(TOP)/mk/beforeauto.mk
include ./dir.mk
include $(TOP)/mk/afterauto.mk
